[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
buildTimeout = 1800  # 30 minutes build timeout

[deploy]
healthcheckPath = "/actuator/health"
healthcheckTimeout = 300
healthcheckInterval = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.healthcheck]
interval = "30s"
timeout = "10s"
retries = 3
startPeriod = "60s" 